backend:
  name: git-gateway
  branch: main

media_library:
  name: uploadcare
  config:
    publicKey: your-public-key

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }